// ── The generated capability table (SERVER ONLY) ─────────────
//
// docs/analyst-capabilities.md is rendered from the registry by
// `npm run analyst:capabilities` and never edited by hand; parity.test.ts fails when
// the committed file differs from this render. Area, capability, tool, parameters,
// what it holds and the privacy category: no value of anyone's health.

import { parameterNames, schemaOfCapability } from './params-text';
import type { Capability } from './types';

type Row = Pick<Capability<never, never>, 'id' | 'area' | 'title' | 'tool' | 'description' | 'category' | 'params'>;

/** A table cell on one line, the pipe escaped. */
const cell = (text: string): string => text.replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();

export function renderCapabilityDoc(caps: readonly Row[]): string {
  const lines = [
    '# Analyst capabilities',
    '',
    '<!-- Generated by `npm run analyst:capabilities` from the capability registry (src/lib/analyst/capabilities). Do not edit by hand: parity.test.ts fails when this file differs from the render. -->',
    '',
    'Everything the AI analyst can read, one row per capability. A model reads these through tool calls, for any day or period; the table shows what each one holds and which privacy category it sends, never a value. Parameters marked with * are required.',
    '',
    '| Area | Capability | Tool | Parameters | What it holds | Privacy category |',
    '|---|---|---|---|---|---|',
  ];
  for (const c of caps) {
    const names = parameterNames(schemaOfCapability(c));
    lines.push(`| ${c.area} | \`${c.id}\` — ${cell(c.title)} | \`${c.tool}\` | ${names.length ? cell(names.join(', ')) : 'none'} | ${cell(c.description)} | \`${c.category}\` |`);
  }
  return `${lines.join('\n')}\n`;
}
