// Reference plan: bodyweight strength with skill progressions, trained on a
// 2-on / 1-off wave while cutting. One example of what the plan model can hold —
// not a default. The analyst adapts or ignores it depending on the user's goal.

const RIR_1_3 = { rpe: [7, 9], rir: [1, 3] };

export function calisthenicsTemplate(startDate: string): unknown {
  return {
    title: '6-month calisthenics progression',
    goal: 'Build bodyweight strength and first skill milestones (pistol squat, pull-up, archer push-up) while losing weight.',
    context: [
      'Cutting at roughly 1.5 lb (0.7 kg) per week.',
      'Sessions stay around 30 minutes with 2–3 exercises.',
      'High daily walking volume; no extra formal cardio.',
    ],
    startDate,
    durationWeeks: 26,
    focusAreas: [
      {
        id: 'push',
        name: 'Push',
        paths: [
          {
            id: 'horizontal-push',
            name: 'Horizontal push',
            model: 'variation',
            priority: 'primary',
            stages: [
              { id: 'incline-push-up', name: 'Incline push-up', match: { names: ['Incline Push Up', 'Incline Push Ups'] },
                prescription: { sets: [3, 4], reps: [8, 15], effort: RIR_1_3 },
                advanceWhen: { sets: [3, 4], reps: [12, 15], effort: RIR_1_3 },
                cues: ['Rigid body line', 'Chest reaches the surface'], checks: ['No wrist or shoulder pain'], expectedWeeks: [2, 4] },
              { id: 'floor-push-up', name: 'Floor push-up', match: { names: ['Push Up', 'Push Ups'] },
                prescription: { sets: [3, 4], reps: [10, 15], effort: RIR_1_3 },
                advanceWhen: { sets: [3, 4], reps: [10, 15], effort: RIR_1_3 },
                cues: ['Chest approaches the floor', 'Body stays rigid', 'No shoulder shrugging'], checks: ['No elbow or wrist pain'], expectedWeeks: [3, 6] },
              { id: 'decline-push-up', name: 'Decline push-up', match: { names: ['Decline Push Up', 'Decline Push Ups'] },
                prescription: { sets: [3, 4], reps: [8, 12], effort: RIR_1_3 },
                advanceWhen: { sets: [3, 4], reps: [8, 12], effort: RIR_1_3 },
                cues: ['Rigid body line', 'Controlled tempo'], checks: ['No shoulder discomfort'], expectedWeeks: [3, 6] },
              { id: 'close-grip-push-up', name: 'Close-grip / diamond push-up', match: { names: ['Diamond Push Up', 'Close Grip Push Up'] },
                prescription: { sets: [3, 3], reps: [8, 12], effort: RIR_1_3 },
                advanceWhen: { sets: [3, 3], reps: [8, 12], effort: RIR_1_3 },
                cues: ['Elbows track back, not out'], checks: ['Elbows and wrists tolerate it', 'No shoulder discomfort'], expectedWeeks: [3, 6] },
              { id: 'archer-push-up', name: 'Archer push-up', match: { names: ['Archer Push Up'] },
                prescription: { sets: [3, 3], reps: [5, 8], perSide: true, effort: RIR_1_3 },
                advanceWhen: { sets: [3, 3], reps: [5, 8], perSide: true, effort: RIR_1_3 },
                cues: ['Working arm does most of the work', 'No twisting through the torso'], checks: ['No shoulder pain'], expectedWeeks: [4, 8] },
              { id: 'assisted-one-arm-push-up', name: 'Assisted one-arm push-up', match: { names: ['One Arm Push Up (Assisted)', 'Incline One Arm Push Up'] },
                prescription: { sets: [3, 5], reps: [3, 6], perSide: true, effort: RIR_1_3 },
                advanceWhen: { sets: [3, 5], reps: [3, 6], perSide: true, effort: RIR_1_3 },
                cues: ['Wide feet', 'Hips stay square'], checks: ['No twisting through the hips', 'No shoulder pain'], expectedWeeks: [6, 12] },
              { id: 'one-arm-push-up', name: 'One-arm push-up', match: { names: ['One Arm Push Up'] },
                prescription: { sets: [3, 3], reps: [1, 5], perSide: true },
                cues: ['Full controlled range'], checks: ['No shoulder pain'] },
            ],
          },
          {
            id: 'vertical-push',
            name: 'Vertical push',
            model: 'variation',
            priority: 'secondary',
            stages: [
              { id: 'pike-push-up', name: 'Pike push-up', match: { names: ['Pike Push Up'] },
                prescription: { sets: [3, 4], reps: [6, 10], effort: RIR_1_3 }, advanceWhen: { sets: [3, 4], reps: [6, 10], effort: RIR_1_3 },
                cues: ['Controlled lowering', 'Head tracks between the hands'], checks: ['No neck or shoulder discomfort'] },
              { id: 'elevated-pike-push-up', name: 'Elevated pike push-up', match: { names: ['Elevated Pike Push Up'] },
                prescription: { sets: [3, 4], reps: [6, 10], effort: RIR_1_3 }, advanceWhen: { sets: [3, 4], reps: [6, 10], effort: RIR_1_3 },
                cues: ['Hips stacked over the hands'], checks: ['No neck or shoulder discomfort'] },
              { id: 'wall-handstand-hold', name: 'Wall handstand hold', match: { names: ['Handstand Hold', 'Wall Handstand Hold'] },
                prescription: { sets: [3, 3], holdS: [20, 40] }, advanceWhen: { sets: [3, 3], holdS: [30, 40] },
                cues: ['Stable shoulder position', 'Controlled exit from the wall'], checks: ['No wrist pain'] },
              { id: 'partial-wall-hspu', name: 'Partial wall handstand push-up', match: { names: ['Handstand Push Up (Partial)'] },
                prescription: { sets: [3, 3], reps: [3, 6], effort: RIR_1_3 }, advanceWhen: { sets: [3, 3], reps: [3, 6], effort: RIR_1_3 },
                cues: ['Controlled descent'], checks: ['No wrist or shoulder pain'] },
              { id: 'wall-hspu', name: 'Full wall handstand push-up', match: { names: ['Handstand Push Up'] },
                prescription: { sets: [3, 3], reps: [1, 5] }, cues: ['Full range'], checks: ['No wrist or shoulder pain'] },
            ],
          },
        ],
      },
      {
        id: 'pull',
        name: 'Pull',
        paths: [
          {
            id: 'pull-up',
            name: 'Pull-up',
            model: 'variation',
            priority: 'primary',
            stages: [
              { id: 'scapular-pull-up', name: 'Scapular pull-up', match: { names: ['Scapular Pull Up'] },
                prescription: { sets: [3, 3], reps: [8, 12] }, advanceWhen: { sets: [3, 3], reps: [8, 12] },
                cues: ['Depress and retract the shoulder blades', 'No elbow bend'], checks: [] },
              { id: 'negative-pull-up', name: 'Negative pull-up', match: { names: ['Negative Pull Up', 'Pull Up (Negative)'] },
                prescription: { sets: [3, 5], reps: [3, 5], eccentricS: [5, 8] }, advanceWhen: { sets: [3, 5], reps: [3, 5], eccentricS: [5, 8] },
                cues: ['5–8 second lowering', 'No uncontrolled drop'], checks: ['No elbow or shoulder irritation'] },
              { id: 'assisted-pull-up', name: 'Assisted pull-up', match: { names: ['Pull Up (Assisted)', 'Assisted Pull Up', 'Band Assisted Pull Up'] },
                prescription: { sets: [3, 4], reps: [5, 8], effort: RIR_1_3 }, advanceWhen: { sets: [3, 4], reps: [5, 8], effort: RIR_1_3 },
                cues: ['Chin clears the bar', 'Controlled lowering', 'Reduce assistance as reps reach 8'], checks: ['No elbow or shoulder irritation'], expectedWeeks: [4, 10] },
              { id: 'pull-up', name: 'Pull-up', match: { names: ['Pull Up'] },
                prescription: { sets: [3, 3], reps: [3, 8], effort: RIR_1_3 }, advanceWhen: { sets: [3, 3], reps: [8, 10], effort: RIR_1_3 },
                steps: [
                  { name: 'First clean rep', advanceWhen: { sets: [1, 1], reps: [1, 1] } },
                  { name: '3×3', advanceWhen: { sets: [3, 3], reps: [3, 3] } },
                  { name: '3×5', advanceWhen: { sets: [3, 3], reps: [5, 5] } },
                  { name: '3×8', advanceWhen: { sets: [3, 3], reps: [8, 8] } },
                ],
                cues: ['Full hang to chin over the bar', 'No kipping'], checks: ['No elbow or shoulder irritation'] },
              { id: 'chest-to-bar', name: 'Chest-to-bar pull-up', match: { names: ['Chest to Bar Pull Up'] },
                prescription: { sets: [3, 3], reps: [3, 6] }, cues: ['Pull the bar to the sternum'], checks: [] },
            ],
          },
          {
            id: 'row',
            name: 'Row',
            model: 'variation',
            priority: 'secondary',
            stages: [
              { id: 'incline-row', name: 'Incline row', match: { names: ['Incline Row'] },
                prescription: { sets: [3, 4], reps: [10, 15] }, advanceWhen: { sets: [3, 4], reps: [12, 15] },
                cues: ['Shoulder blades retract', 'Body stays rigid'], checks: [] },
              { id: 'horizontal-row', name: 'Horizontal row', match: { names: ['Inverted Row', 'Ring Row'] },
                prescription: { sets: [3, 4], reps: [8, 12] }, advanceWhen: { sets: [3, 4], reps: [10, 12] },
                cues: ['Full range', 'No shrugging'], checks: [] },
              { id: 'feet-elevated-row', name: 'Feet-elevated row', match: { names: ['Feet Elevated Inverted Row'] },
                prescription: { sets: [3, 3], reps: [8, 12] }, cues: ['Pause at the top', 'No hip sag'], checks: [] },
            ],
          },
        ],
      },
      {
        id: 'lower',
        name: 'Lower body',
        paths: [
          {
            id: 'squat-to-pistol',
            name: 'Squat to pistol squat',
            model: 'variation',
            priority: 'primary',
            stages: [
              { id: 'bodyweight-squat', name: 'Bodyweight squat', match: { names: ['Bodyweight Squat', 'Air Squat', 'Squat (Bodyweight)'] },
                prescription: { sets: [3, 4], reps: [15, 20] }, advanceWhen: { sets: [3, 4], reps: [15, 20] },
                cues: ['Knees track over toes', 'Heels stay down'], checks: ['No knee or hip discomfort'], expectedWeeks: [2, 4] },
              { id: 'pause-squat', name: 'Pause / tempo squat', match: { names: ['Pause Squat', 'Tempo Squat'] },
                prescription: { sets: [3, 3], reps: [10, 15] }, advanceWhen: { sets: [3, 3], reps: [12, 15] },
                cues: ['1–2 second pause at the bottom', 'No bouncing'], checks: [], expectedWeeks: [2, 4] },
              { id: 'split-squat', name: 'Split squat', match: { names: ['Split Squat'] },
                prescription: { sets: [3, 4], reps: [10, 15], perSide: true }, advanceWhen: { sets: [3, 4], reps: [12, 15], perSide: true },
                cues: ['Back knee approaches the floor', 'Front knee tracks cleanly'], checks: ['No knee pain'], expectedWeeks: [3, 6] },
              { id: 'bulgarian-split-squat', name: 'Bulgarian split squat', match: { names: ['Bulgarian Split Squat'] },
                prescription: { sets: [3, 4], reps: [8, 12], perSide: true }, advanceWhen: { sets: [3, 4], reps: [10, 12], perSide: true },
                cues: ['Deep controlled range'], checks: ['No knee or hip irritation'], expectedWeeks: [4, 8] },
              { id: 'box-pistol-squat', name: 'Box pistol squat', match: { names: ['Box Pistol Squat', 'Pistol Squat (Box)'] },
                prescription: { sets: [3, 3], reps: [5, 8], perSide: true }, advanceWhen: { sets: [3, 3], reps: [5, 8], perSide: true },
                steps: [{ name: 'High box' }, { name: 'Chair height' }, { name: 'Low box' }, { name: 'Very low box' }],
                cues: ['Smooth controlled descent', 'No heavy push off support'], checks: ['No knee pain'], expectedWeeks: [4, 12] },
              { id: 'assisted-pistol-squat', name: 'Assisted pistol squat', match: { names: ['Assisted Pistol Squat', 'Pistol Squat (Assisted)'] },
                prescription: { sets: [3, 5], reps: [3, 6], perSide: true }, advanceWhen: { sets: [3, 5], reps: [3, 6], perSide: true },
                cues: ['Light fingertip assistance only', 'No bouncing out of the bottom'], checks: ['No knee cave'], expectedWeeks: [4, 12] },
              { id: 'pistol-squat', name: 'Pistol squat', match: { names: ['Pistol Squat'] },
                prescription: { sets: [3, 3], reps: [1, 8], perSide: true },
                steps: [
                  { name: 'First clean rep', advanceWhen: { sets: [1, 1], reps: [1, 1], perSide: true } },
                  { name: '3×3', advanceWhen: { sets: [3, 3], reps: [3, 3], perSide: true } },
                  { name: '3×5', advanceWhen: { sets: [3, 3], reps: [5, 5], perSide: true } },
                  { name: '3×8', advanceWhen: { sets: [3, 3], reps: [8, 8], perSide: true } },
                ],
                cues: ['Heel stays down', 'Controlled ascent'], checks: ['No knee pain'] },
            ],
          },
        ],
      },
      {
        id: 'core',
        name: 'Core',
        paths: [
          {
            id: 'core',
            name: 'Core',
            model: 'variation',
            priority: 'primary',
            stages: [
              { id: 'dead-bug', name: 'Dead bug', match: { names: ['Dead Bug'] },
                prescription: { sets: [3, 3], reps: [8, 12], perSide: true }, advanceWhen: { sets: [3, 3], reps: [10, 12], perSide: true },
                cues: ['Low back stays controlled'], checks: ['No hip or back discomfort'] },
              { id: 'plank', name: 'Plank', match: { names: ['Plank'] },
                prescription: { sets: [3, 3], holdS: [45, 60] }, advanceWhen: { sets: [3, 3], holdS: [55, 60] },
                cues: ['No hip sag', 'Controlled breathing'], checks: ['No low-back discomfort'] },
              { id: 'hollow-hold', name: 'Hollow hold', match: { names: ['Hollow Body Hold', 'Hollow Hold', 'Hollow Tuck Hold'] },
                prescription: { sets: [3, 3], holdS: [20, 30] }, advanceWhen: { sets: [3, 3], holdS: [25, 30] },
                cues: ['Low back pressed down'], checks: [] },
              { id: 'reverse-crunch', name: 'Reverse crunch', match: { names: ['Reverse Crunch'] },
                prescription: { sets: [3, 3], reps: [10, 15], effort: RIR_1_3 }, advanceWhen: { sets: [3, 3], reps: [12, 15], effort: RIR_1_3 },
                cues: ['Pelvis curls upward', 'No momentum'], checks: ['No low-back discomfort'] },
              { id: 'hanging-knee-raise', name: 'Hanging knee raise', match: { names: ['Hanging Knee Raise'] },
                prescription: { sets: [3, 3], reps: [8, 12] }, advanceWhen: { sets: [3, 3], reps: [10, 12] },
                cues: ['No swinging', 'Shoulders stay active'], checks: [] },
              { id: 'hanging-leg-raise', name: 'Hanging leg raise', match: { names: ['Hanging Leg Raise'] },
                prescription: { sets: [3, 3], reps: [6, 10] }, advanceWhen: { sets: [3, 3], reps: [8, 10] },
                cues: ['Controlled tempo'], checks: ['No grip, elbow or shoulder irritation'] },
              { id: 'l-sit', name: 'L-sit progression', match: { names: ['L-Sit', 'Tuck L-Sit'] },
                prescription: { sets: [3, 3], holdS: [10, 20] },
                steps: [{ name: 'Tuck support hold' }, { name: 'One-leg extended' }, { name: 'Tucked L-sit' }, { name: 'Full L-sit' }],
                cues: ['Locked elbows', 'Shoulders depressed'], checks: ['No wrist pain'] },
            ],
          },
        ],
      },
    ],
    rules: {
      qualifyingSessions: [2, 3],
      effort: RIR_1_3,
      lights: {
        green: [
          'Target reps and sets achieved for 2–3 workouts',
          'Movement smooth and controlled through full range',
          'No joint pain; recovery stable',
          'Most sets still leave at least 1 rep in reserve',
        ],
        yellow: [
          'Reps achieved but form inconsistent',
          'One side much weaker, or momentum needed',
          'Recovery okay but not great; minor discomfort that fades quickly',
        ],
        red: ['Sharp or lingering joint pain', 'Repeated strength drops', 'Poor sleep or constantly heavy legs', 'Dread around training'],
      },
      doNotProgressIf: [
        'Reps are shaky or inconsistent',
        'Range of motion is reduced',
        'Knees, elbows, wrists or shoulders hurt',
        'Soreness persists when the pattern comes around again',
      ],
      deload: { everyWeeks: [4, 6], volumeReduction: [0.3, 0.5] },
      recoveryGates: [
        { signal: 'resting_hr', rule: 'rising', threshold: 3, severity: 'watch', note: 'Resting heart rate trending up is a deload sign.' },
        { signal: 'hrv', rule: 'falling', threshold: 10, severity: 'watch' },
        { signal: 'sleep_hours', rule: 'below', threshold: 6, severity: 'warn', note: 'Poor sleep is a reason to hold, not progress.' },
        { signal: 'body_weight_rate', rule: 'below', threshold: -0.9, severity: 'watch', note: 'Losing faster than ~2 lb/week makes recovery harder.' },
      ],
    },
    blocks: [
      { id: 'month-1', name: 'Month 1: Foundation and form', startWeek: 1, weeks: 4, kind: 'build',
        goals: ['Clean push-ups or incline push-ups', 'Clean bodyweight squats', 'Rows', 'Plank and dead-bug basics'],
        targets: [
          { pathId: 'squat-to-pistol', label: 'Squat 3×15–20', dose: { sets: [3, 3], reps: [15, 20] } },
          { pathId: 'horizontal-push', label: 'Push-up variation 3×8–12', dose: { sets: [3, 3], reps: [8, 12] } },
          { pathId: 'row', label: 'Row 3×8–12', dose: { sets: [3, 3], reps: [8, 12] } },
          { pathId: 'core', label: 'Plank 3×45–60 s', dose: { sets: [3, 3], holdS: [45, 60] } },
        ] },
      { id: 'month-2', name: 'Month 2: Controlled strength', startWeek: 5, weeks: 4, kind: 'build',
        goals: ['Pause squats', 'Split squats', 'Stronger push-ups', 'Hollow-body control'],
        targets: [
          { pathId: 'squat-to-pistol', label: 'Split squat 3×10–12/leg' },
          { pathId: 'horizontal-push', label: 'Push-up 3×10–15' },
          { pathId: 'core', label: 'Hollow hold 3×20–30 s' },
        ] },
      { id: 'month-3', name: 'Month 3: Unilateral strength', startWeek: 9, weeks: 5, kind: 'build',
        goals: ['Bulgarian split squats', 'Decline or close-grip push-ups', 'Negative or assisted pull-ups', 'Hanging core'],
        targets: [
          { pathId: 'squat-to-pistol', label: 'Bulgarian split squat 3×8–12/leg' },
          { pathId: 'horizontal-push', label: 'Decline push-up 3×8–12' },
          { pathId: 'pull-up', label: 'Negatives 3–5 × 5–8 s lowering' },
        ] },
      { id: 'month-4', name: 'Month 4: Skill-specific progressions', startWeek: 14, weeks: 4, kind: 'build',
        goals: ['Box pistol squats', 'Archer push-up intro', 'Assisted or first pull-ups', 'Pike push-ups'],
        targets: [
          { pathId: 'squat-to-pistol', label: 'Box pistol 3×5–8/leg' },
          { pathId: 'horizontal-push', label: 'Archer push-up 3×4–6/side' },
          { pathId: 'pull-up', label: 'Assisted pull-up 3×5–8' },
          { pathId: 'vertical-push', label: 'Pike push-up 3×6–10' },
        ] },
      { id: 'month-5', name: 'Month 5: Lower assistance', startWeek: 18, weeks: 5, kind: 'build',
        goals: ['Lower box pistol height', 'Lighter assisted pistols', 'More pull-up volume'],
        targets: [
          { pathId: 'squat-to-pistol', label: 'Assisted pistol 3×3–6/leg' },
          { pathId: 'pull-up', label: 'Pull-up toward 3×3–5' },
        ] },
      { id: 'month-6', name: 'Month 6: Consolidation', startWeek: 23, weeks: 4, kind: 'build',
        goals: ['First full pistol attempts if ready', 'Build pull-up strength', 'One advanced push goal'],
        targets: [
          { pathId: 'squat-to-pistol', label: 'First clean pistol, or 3×3 assisted' },
          { pathId: 'pull-up', label: 'Pull-up 3×5+' },
        ] },
    ],
    templates: [
      { id: 'a', name: 'Workout A: Upper body', minutes: 30,
        warmup: ['Wrist circles', 'Shoulder circles', 'Scapular push-ups', 'Active hangs', '1 easy push-up set'],
        slots: [
          { pathIds: ['horizontal-push'] },
          { pathIds: ['pull-up'] },
          { pathIds: ['row', 'vertical-push', 'core'], optional: true, rotate: true, note: 'Skip if time or recovery is limited.' },
        ] },
      { id: 'b', name: 'Workout B: Lower body & core', minutes: 30,
        warmup: ['Hip hinges', 'Glute bridges', 'Bodyweight squats', 'Ankle rocks'],
        slots: [
          { pathIds: ['squat-to-pistol'] },
          { pathIds: ['core'] },
        ] },
    ],
    schedule: { kind: 'cycle', days: ['a', 'b', 'rest'], advance: 'on-completion' },
  };
}
