// ── Analyst service (SPEC §8) ───────────────────────────
//
// The single entry point for the analyst feature. It runs on the server only:
// the API route calls `askAnalyst`, and the browser never touches a provider,
// a credential or the dataset directly.
//
// Guarantees enforced here:
//   * the query is read-only and bounded (length, characters, no instructions)
//   * retrieval selects only the summaries the question needs
//   * imported notes are treated as untrusted DATA, never as instructions
//   * no health value is ever written to a log
//   * a configured provider is named, and every answer states which provider and
//     model produced it — that provenance is not a permission gate
//   * a model reply is parsed and validated before it becomes an answer, and its
//     numeric claims are audited against the selected context
//   * a misconfigured or failing provider says so — it never falls back to demo
//     output and canned text is never presented as a live model response

import { REFERENCE_KEY } from '../adapters/dataset';
import type { UnitSystem } from '../prefs';
import { getMetric } from '../metrics/registry';
import { selectHandler, selectHandlerStrict } from './handlers';
import { SUPPORTED_PROMPTS } from './prompts';
import {
  AnalysisNotAvailable,
  DEFAULT_LAB_SPEC,
  GENERAL_HANDLER_ID,
  labSpecOf,
  retrieve,
  retrieveGeneral,
} from './retrieval';
import { loadLabSnapshot, type LabLoader } from './labContext';
import { AnalystProviderError, createProvider, DEMO_LABEL, supportsStreaming } from './provider';
import { parseAnalystSse } from './stream';
import { readAnalystConfig, type AnalystConfig } from './config';
import { checkGrounding, parseAnalystReply } from './validate';
import { boundedHistory, type ChatTurn } from './memory';
import type {
  AnalystAnswer,
  AnalystGrounding,
  AnalystProviderContext,
  AnalystRequest,
  AnalystResponse,
  AnalystStatus,
  LabContextSnapshot,
  RetrievalBundle,
} from './types';

export const QUERY_MAX_CHARS = 400;
export const NOTES_MAX_CHARS = 1000;

export const EDUCATIONAL_NOTICE =
  'Educational information about your own recorded data. Not medical advice, not a diagnosis, and not a substitute for a clinician.';

const DEMO_NOTICE =
  'Demo analyst — no AI provider is configured, so every answer below is computed from your dataset by deterministic handlers with pattern-matching question routing, not generated by a language model.';

const NO_GROUNDING: AnalystGrounding = { checked: 0, unmatched: [] };

// ── Input validation ────────────────────────────────────

export interface ValidatedQuery {
  ok: boolean;
  query: string;
  reason: string | null;
}

/** Read-only, bounded validation of the incoming question. */
export function validateQuery(raw: unknown): ValidatedQuery {
  if (typeof raw !== 'string') return { ok: false, query: '', reason: 'The question must be text.' };
  // Strip control characters before anything else.
  const cleaned = raw.replace(/[\u0000-\u001F\u007F]/g, ' ').trim();
  if (cleaned.length === 0) return { ok: false, query: '', reason: 'Enter a question to ask.' };
  if (cleaned.length > QUERY_MAX_CHARS) {
    return {
      ok: false,
      query: cleaned.slice(0, QUERY_MAX_CHARS),
      reason: `Questions are limited to ${QUERY_MAX_CHARS} characters; this one was ${cleaned.length}.`,
    };
  }
  return { ok: true, query: cleaned, reason: null };
}

export interface SanitizedNotes {
  received: boolean;
  characters: number;
  /** The notes are kept as opaque text. They are never parsed or executed. */
  text: string;
  truncated: boolean;
  note: string;
}

/**
 * Imported notes are untrusted data. They are length-capped, stripped of
 * control characters and kept as opaque text: nothing in them is interpreted as
 * an instruction, and they are never used to compute an answer.
 */
export function sanitizeUntrustedNotes(raw: unknown): SanitizedNotes {
  if (typeof raw !== 'string' || raw.trim().length === 0) {
    return { received: false, characters: 0, text: '', truncated: false, note: 'No imported notes were attached to this question.' };
  }
  const cleaned = raw.replace(/[\u0000-\u001F\u007F]/g, ' ').trim();
  const truncated = cleaned.length > NOTES_MAX_CHARS;
  const text = truncated ? cleaned.slice(0, NOTES_MAX_CHARS) : cleaned;
  return {
    received: true,
    characters: text.length,
    text,
    truncated,
    note: `Notes are treated as untrusted data: ${text.length} characters received${truncated ? ` (truncated from ${cleaned.length})` : ''}. They are never followed as instructions and are not used to compute any figure in this answer.`,
  };
}

// ── Service ─────────────────────────────────────────────

/** Label shown in the UI: never a key, never a plain "remote". */
function labelFor(config: AnalystConfig): string {
  if (config.misconfiguredReason) return `${config.providerDisplayName} (misconfigured)`;
  return config.provider === 'demo' ? DEMO_LABEL : config.providerDisplayName;
}

function baseResponse(config: AnalystConfig, status: AnalystStatus, fields: Partial<AnalystResponse> = {}): AnalystResponse {
  return {
    status,
    label: labelFor(config),
    provider: config.provider,
    providerLabel: config.providerDisplayName,
    providerDisplayName: config.providerDisplayName,
    model: config.provider === 'demo' ? null : config.model,
    providerConfigured: config.provider !== 'demo' && config.misconfiguredReason === null,
    systemPromptSource: config.provider === 'demo' ? 'built-in' : config.systemPromptSource,
    misconfiguredReason: config.misconfiguredReason,
    handlerId: 'none',
    answer: null,
    message: null,
    suggested: SUPPORTED_PROMPTS,
    notice: config.provider === 'demo' ? DEMO_NOTICE : EDUCATIONAL_NOTICE,
    retrieval: { recordsRead: 0, note: 'No dataset context was selected.', metrics: [] },
    grounding: NO_GROUNDING,
    untrustedNotes: { received: false, characters: 0, note: 'No imported notes were attached to this question.' },
    ...fields,
  };
}

/**
 * The lab half of the selection note. It states, in words, what the block
 * carries and why — never silently omitting that lab data exists or that none
 * could be read.
 */
function labSentence(lab: LabContextSnapshot): string {
  if (!lab.available) return ` Lab results are not in this context: ${lab.reason}`;
  return ` Lab results: ${lab.note}; ${lab.documents} document${lab.documents === 1 ? '' : 's'} and ${lab.totalObservations} lab observation${lab.totalObservations === 1 ? '' : 's'} across ${lab.totalSeries} series were read.`;
}

function retrievalSummary(bundle: RetrievalBundle | null): AnalystResponse['retrieval'] {
  if (!bundle) return { recordsRead: 0, note: 'No dataset context was selected.', metrics: [] };
  return {
    recordsRead: bundle.recordsRead,
    note: bundle.note,
    metrics: bundle.summaries.map(s => ({
      metricId: s.metricId,
      window: `${s.lengthLabel} (${s.window.startKey} → ${s.window.endKey})`,
      observations: s.counts.evaluated,
    })),
  };
}

export type AnalystStreamChunk =
  | { kind: 'reasoning'; text: string }
  | { kind: 'answer'; text: string }
  | { kind: 'result'; response: AnalystResponse };

interface Prepared {
  ok: true;
  config: AnalystConfig;
  query: string;
  notes: SanitizedNotes;
  notesEcho: AnalystResponse['untrustedNotes'];
  bundle: RetrievalBundle;
  handlerId: string;
  system: UnitSystem;
  history: ChatTurn[];
}

type Preparation = Prepared | { ok: false; response: AnalystResponse };

/**
 * Everything both the non-streaming and the streaming path need before a
 * provider is contacted: validation, routing, retrieval, the bounded lab block,
 * the resolved provider configuration, the unit system and the bounded history.
 *
 * Kept in one place so the two paths cannot drift — a question the service
 * refuses is refused identically whether it was asked over SSE or not. A refusal
 * or a misconfiguration comes back as `ok: false` with the finished response,
 * and no provider was created.
 */
async function prepareAnalyst(
  request: AnalystRequest,
  deps: { env?: NodeJS.ProcessEnv; labLoader?: LabLoader }
): Promise<Preparation> {
  const config = readAnalystConfig(deps.env ?? process.env);
  const validated = validateQuery(request?.query);
  const notes = sanitizeUntrustedNotes(request?.notes);
  const notesEcho = { received: notes.received, characters: notes.characters, note: notes.note };
  const base = (status: AnalystStatus, fields: Partial<AnalystResponse> = {}) =>
    baseResponse(config, status, { untrustedNotes: notesEcho, ...fields });

  if (!validated.ok) return { ok: false, response: base('error', { message: validated.reason }) };

  // A provider is named but cannot be used: state why, compute nothing, send nothing.
  if (config.misconfiguredReason) {
    return {
      ok: false,
      response: base('misconfigured', {
        message: `${config.misconfiguredReason} No request was sent and no answer was computed.`,
      }),
    };
  }

  const isDemo = config.provider === 'demo';
  const matched = isDemo ? selectHandler(validated.query) : selectHandlerStrict(validated.query);

  if (isDemo && !matched) {
    return {
      ok: false,
      response: base('unsupported', {
        message: `The demo analyst matches questions by pattern, so it cannot route "${validated.query}". Nothing was computed or sent. Try one of the supported questions below.`,
      }),
    };
  }

  let bundle: RetrievalBundle;
  try {
    bundle = matched ? retrieve(matched.id, REFERENCE_KEY) : retrieveGeneral(REFERENCE_KEY);
  } catch (error) {
    if (error instanceof AnalysisNotAvailable) return { ok: false, response: base('error', { message: error.message }) };
    throw error;
  }
  const handlerId = matched?.id ?? GENERAL_HANDLER_ID;

  const labSpec = labSpecOf(handlerId) ?? DEFAULT_LAB_SPEC;
  let lab: LabContextSnapshot | null = null;
  try {
    lab = await (deps.labLoader ?? loadLabSnapshot)(validated.query, labSpec);
  } catch {
    lab = null;
  }
  if (lab) {
    bundle = {
      ...bundle,
      lab,
      recordsRead: bundle.recordsRead + (lab.available ? lab.totalObservations : 0),
      note: `${bundle.note}${labSentence(lab)}`,
    };
  }

  const system: UnitSystem = request?.system === 'imperial' ? 'imperial' : 'metric';
  const history = boundedHistory(request?.history);

  return { ok: true, config, query: validated.query, notes, notesEcho, bundle, handlerId, system, history };
}

/** Build the provider request context from a prepared analyst question. */
function providerContext(prep: Prepared): AnalystProviderContext {
  return {
    refKey: REFERENCE_KEY,
    system: prep.system,
    bundle: prep.bundle,
    question: prep.query,
    prompt: prep.config.systemPrompt,
    notes: prep.notes.text.length > 0 ? prep.notes.text : undefined,
    history: prep.history,
  };
}

/**
 * Ask the analyst a question.
 *
 * With no provider configured this is deterministic, offline and read-only. With
 * a provider configured the same request goes to that provider — a configured
 * provider is used directly — and the reply is validated before it is returned.
 *
 * `deps.env` exists so the provider configuration can be injected in tests; in
 * production it defaults to the server process environment.
 */
export async function askAnalyst(
  request: AnalystRequest,
  deps: { env?: NodeJS.ProcessEnv; labLoader?: LabLoader } = {}
): Promise<AnalystResponse> {
  const prep = await prepareAnalyst(request, deps);
  if (!prep.ok) return prep.response;

  const { config, bundle, handlerId, notesEcho } = prep;
  const base = (status: AnalystStatus, fields: Partial<AnalystResponse> = {}) =>
    baseResponse(config, status, { untrustedNotes: notesEcho, ...fields });
  const withContext = {
    handlerId,
    retrieval: retrievalSummary(bundle),
  };

  let provider;
  try {
    provider = createProvider(config);
  } catch (error) {
    return base('misconfigured', {
      handlerId,
      message: error instanceof Error ? error.message : 'The configured provider could not be created.',
    });
  }

  let answer: AnalystAnswer | null = null;
  let grounding: AnalystGrounding = NO_GROUNDING;

  try {
    const result = await provider.answer(providerContext(prep));

    if (!result) {
      return base('unsupported', {
        ...withContext,
        message: 'That handler produced no answer from the selected context.',
      });
    }

    if (result.kind === 'answer') {
      // The demo provider computes its answer from the bundle, so there is no
      // model text to audit: the grounding check applies to model replies.
      answer = result.answer;
    } else {
      const parsed = parseAnalystReply(result.text, { bundle });
      if (!parsed.ok || !parsed.answer) {
        return base('error', {
          ...withContext,
          message: parsed.reason ?? "The model's reply could not be read as an answer.",
        });
      }
      answer = parsed.answer;
      grounding = checkGrounding(answer, bundle, prep.system);
    }
  } catch (error) {
    if (error instanceof AnalystProviderError) {
      // The message is already scrubbed by the provider (no key, no credential URL).
      return base('error', { ...withContext, message: error.message });
    }
    throw error;
  }

  return base('ok', {
    ...withContext,
    answer,
    message: null,
    grounding,
  });
}

/**
 * Ask the analyst and stream the reply as it is produced.
 *
 * Yields reasoning and answer fragments separately, then exactly one `result`
 * chunk carrying the finished `AnalystResponse` — the same shape `askAnalyst`
 * returns, built by the same validation. The assembled ANSWER text (never the
 * reasoning) is what is parsed, guarded and presented; reasoning is streamed for
 * display only and is never promoted into an answer.
 *
 * When the provider cannot stream (the demo provider, or an endpoint that does
 * not speak this wire format), the non-streaming answer is computed and a single
 * `result` chunk is yielded — the caller re-emits it, so the stream route still
 * works everywhere.
 *
 * The caller owns the upstream connection: it must call the returned `abort` when
 * it stops early. `abort` is a no-op once the stream has finished.
 */
export function streamAnalyst(
  request: AnalystRequest,
  deps: { env?: NodeJS.ProcessEnv; labLoader?: LabLoader } = {}
): { chunks: AsyncGenerator<AnalystStreamChunk>; abort: () => void } {
  let abortUpstream: (() => void) | null = null;

  async function* run(): AsyncGenerator<AnalystStreamChunk> {
    const prep = await prepareAnalyst(request, deps);
    if (!prep.ok) {
      yield { kind: 'result', response: prep.response };
      return;
    }

    const { config, bundle, handlerId, notesEcho } = prep;
    const base = (status: AnalystStatus, fields: Partial<AnalystResponse> = {}) =>
      baseResponse(config, status, { untrustedNotes: notesEcho, ...fields });
    const withContext = { handlerId, retrieval: retrievalSummary(bundle) };

    let provider;
    try {
      provider = createProvider(config);
    } catch (error) {
      yield {
        kind: 'result',
        response: base('misconfigured', {
          handlerId,
          message: error instanceof Error ? error.message : 'The configured provider could not be created.',
        }),
      };
      return;
    }

    // A provider that cannot stream still gets an answer; it just arrives in one
    // chunk. Nothing is faked about it.
    if (!supportsStreaming(provider)) {
      const response = await askAnalyst(request, deps);
      yield { kind: 'result', response };
      return;
    }

    const context = providerContext(prep);
    const { system, user } = provider.messagesFor(context);
    let handle;
    try {
      handle = await provider.answerStream(system, user);
    } catch (error) {
      if (error instanceof AnalystProviderError) {
        yield { kind: 'result', response: base('error', { ...withContext, message: error.message }) };
        return;
      }
      throw error;
    }
    abortUpstream = handle.abort;

    let assembled = '';
    let model: string | null = null;
    let finishReason: string | null = null;
    let reasoningTokens: number | null = null;

    try {
      for await (const event of parseAnalystSse(handle.response.body as ReadableStream<Uint8Array>)) {
        if (event.kind === 'reasoning') {
          yield { kind: 'reasoning', text: event.text };
        } else if (event.kind === 'answer') {
          assembled += event.text;
          yield { kind: 'answer', text: event.text };
        } else {
          if (event.model) model = event.model;
          finishReason = event.finishReason;
          reasoningTokens = event.reasoningTokens;
        }
      }
    } catch (error) {
      // A stream that broke mid-flight is reported, not silently truncated. The
      // client falls back to the non-streaming endpoint from here.
      handle.abort();
      const detail =
        error instanceof AnalystProviderError
          ? error.message
          : `The provider at ${config.endpointHost ?? 'the configured endpoint'} ended the stream early.`;
      yield { kind: 'result', response: base('error', { ...withContext, message: detail }) };
      return;
    } finally {
      abortUpstream = null;
    }

    // The assembled answer text runs through exactly the same guard as a
    // non-streamed reply: the numeric audit and the JSON/shape validation fail
    // closed, and reasoning text was never part of `assembled`.
    const trimmed = assembled.trim();
    if (!trimmed) {
      yield {
        kind: 'result',
        response: base('error', {
          ...withContext,
          message:
            finishReason === 'length' && (reasoningTokens ?? 0) > 0
              ? `The provider spent its whole ${config.maxTokens} token budget on the model's reasoning and never began an answer, so there was nothing to validate. Raise ANALYST_MAX_TOKENS, lower ANALYST_REASONING_EFFORT, or ask a narrower question.`
              : `The provider streamed no answer text${finishReason === 'length' ? ` and stopped at the ${config.maxTokens} token limit` : ''}, so there was nothing to validate.`,
        }),
      };
      return;
    }

    const parsed = parseAnalystReply(trimmed, { bundle });
    if (!parsed.ok || !parsed.answer) {
      yield {
        kind: 'result',
        response: base('error', {
          ...withContext,
          message: parsed.reason ?? "The model's reply could not be read as an answer.",
        }),
      };
      return;
    }

    yield {
      kind: 'result',
      response: base('ok', {
        ...withContext,
        answer: parsed.answer,
        message: null,
        grounding: checkGrounding(parsed.answer, bundle, prep.system),
        // The streaming path reports the model the provider named, so the
        // attribution line matches what the answer view shows.
        model: model ?? config.model,
      }),
    };
  }

  return {
    chunks: run(),
    abort: () => abortUpstream?.(),
  };
}

/** The prompt list a caller may offer, generated from the handler registry. */
export function supportedPrompts(): string[] {
  return SUPPORTED_PROMPTS;
}

/** Metric display names for the selected context, used by the UI panel. */
export function selectedMetricNames(bundle: RetrievalBundle): string[] {
  return [...new Set(bundle.summaries.map(s => getMetric(s.metricId)?.displayName ?? s.metricId))];
}
